[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black>=22.12.0",
    "ipython>=8.9.0",
    "jupyter>=1.0.0",
    "notebook>=6.5.2",
    "pip>=23.0",
    "ruff>=0.0.239",
    "pyright>=1.1.291",
    "isort>=5.12.0",
    # "scipy>=1.9.3",
    "specutils>=1.10.0",
]

[project]
name = "pfs_etc_web"
version = "0.1.0"
description = ""
authors = [{ name = "Masato Onodera", email = "monodera@naoj.org" }]
dependencies = [
    "panel>=1",
    "numpy>=1.24.1",
    "astropy>=5.2.1",
    "pandas>=1.5.3",
    "logzero>=1.7.0",
    "matplotlib>=3.6.3",
    "setuptools==56.1.0",
    "pfsspecsim @ git+https://github.com/Subaru-PFS/spt_ExposureTimeCalculator.git@u/monodera/20230116",
    "synphot>=1.2.0",
    "fastapi>=0.89.1",
    "jinja2>=3.1.2",
    "uvicorn[standard]>=0.20.0",
    "gunicorn>=20.1.0",
    "myst-parser>=1.0.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
run_pfs_etc_web = "pfs_etc_web.cli.run_panel_server:main"
run_test_template = "pfs_etc_web.cli.run_test_template:main"

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.setuptools]
package-dir = { "" = "src" }


# [tool.ruff]
# ignore-init-module-imports = true
# unfixable = ["F401"]
