site_name: PFS Spectral Simulator
site_url: https://example.com
site_author: 'Masato Onodera'

nav:
  - 'Home': index.md
  - 'Inputs': inputs.md
  - 'Execution': exec.md
  - 'Outputs': outputs.md

use_directory_urls: false

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_autoplay: True
      video_muted: True

theme:
  name: material
  palette:
    scheme: pfs
    # primary: custom
  icon:
    logo: material/library
  font:
    text: Lato
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.suggest


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js