site_name: PFS Spectral Simulator
site_url: https://example.com
site_author: 'Masato Onodera'

nav:
  - 'Home': index.md
  - 'Inputs': inputs.md
  - 'Execution': exec.md
  - 'Outputs': outputs.md

use_directory_urls: false

theme:
  name: material
  palette:
    scheme: pfs
    # primary: custom
  font:
    text: Lato
  features:
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - search.highlight

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js