site_name: PFS Spectral Simulator User Guide
site_url: https://pfs-etc.naoj.hawaii.edu/etc/doc/
site_author: 'Masato Onodera'

# repo_url: https://github.com/Subaru-PFS/spt_etc_webapp/

copyright: Copyright &copy; <a href="https://subarutelescope.org">Subaru Telescope</a>, <a href="https://www.nao.ac.jp">NAOJ</a>

nav:
  - 'Home': index.md
  - 'Inputs': inputs.md
  - 'Run Simulation': exec.md
  - 'Outputs': outputs.md
  - 'FAQ and Known Issues': issues.md
  - 'Contact': contact.md

use_directory_urls: false

plugins:
  - search
  - social
  - mkdocs-video:
      is_video: True
      video_autoplay: True
      video_muted: True

theme:
  name: material
  palette:
    scheme: pfs
  icon:
    logo: material/library
  font:
    text: Lato
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Subaru-PFS/spt_etc_webapp/
      name: Subaru-PFS/spt_etc_webapp on GitHub