site_name: PFS Spectral Simulator Documentation
site_url: https://example.com
site_author: 'Masato Onodera'

nav:
  - 'Home': index.md
  - 'Inputs': inputs.md
  - 'Execution': exec.md
  - 'Outputs': outputs.md
  - 'Contact': contact.md

use_directory_urls: false

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_autoplay: True
      video_muted: True

theme:
  name: material
  palette:
    scheme: pfs
    # primary: custom
  icon:
    logo: material/library
  font:
    text: Lato
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select


markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js